#!/usr/bin/env bash
# Produces one 1D scan plot per POI using the ROOT files generated by run_1D_scan.sh.
#
# Usage:
#   bash run_plot_1D_scans.sh [METHOD]
#   METHOD ∈ {CutBased, BDT, DNN, GATO}  (default: CutBased)
set -euo pipefail

: "${HZZ_ROOT:=/afs/cern.ch/work/z/zhiheng/Thesis/HZZAnalysis}"
METHOD="${1:-CutBased}"
TRIAL_DIR="${HZZ_ROOT}/InferenceModel/Results/${METHOD}"
PLOT_SCRIPT="${HZZ_ROOT}/InferenceModel/functions/plot_1D_scan.py"
PLOT_DIR="${TRIAL_DIR}/fit_plots"

mkdir -p "${PLOT_DIR}"

POIS=(
	r_proc_GG2H_0J_PTH_0_10
	r_proc_GG2H_0J_PTH_GT10
	r_proc_GG2H_1J_PTH_0_60
	r_proc_GG2H_1J_PTH_120_200
	r_proc_GG2H_1J_PTH_60_120
	r_proc_GG2H_GE2J_MJJ_0_350_PTH_0_60
	r_proc_GG2H_GE2J_MJJ_0_350_PTH_120_200
	r_proc_GG2H_GE2J_MJJ_0_350_PTH_60_120
	r_proc_GG2H_GE2J_MJJ_GT350
	r_proc_GG2H_PTH_GT200
	r_proc_TTH
	r_proc_VBF_GE2J_MJJ_350_700_PTH_0_200_PTHJJ_0_25
	r_proc_VBF_GE2J_MJJ_60_120
	r_proc_VBF_GE2J_MJJ_GT350_PTH_0_200_PTHJJ_GT25
	r_proc_VBF_GE2J_MJJ_GT350_PTH_GT200
	r_proc_VBF_GE2J_MJJ_GT700_PTH_0_200_PTHJJ_0_25
	r_proc_VBF_rest
	r_proc_WminusH_lep_PTV_0_150
	r_proc_WminusH_lep_PTV_GT150
	r_proc_WminushadH_GE2J_MJJ_350_700_PTH_0_200_PTHJJ_0_25
	r_proc_WminushadH_GE2J_MJJ_60_120
	r_proc_WminushadH_GE2J_MJJ_GT350_PTH_0_200_PTHJJ_GT25
	r_proc_WminushadH_GE2J_MJJ_GT350_PTH_GT200
	r_proc_WminushadH_GE2J_MJJ_GT700_PTH_0_200_PTHJJ_0_25
	r_proc_WminushadH_rest
	r_proc_WplusH_lep_PTV_0_150
	r_proc_WplusH_lep_PTV_GT150
	r_proc_WplushadH_GE2J_MJJ_350_700_PTH_0_200_PTHJJ_0_25
	r_proc_WplushadH_GE2J_MJJ_60_120
	r_proc_WplushadH_GE2J_MJJ_GT350_PTH_0_200_PTHJJ_GT25
	r_proc_WplushadH_GE2J_MJJ_GT350_PTH_GT200
	r_proc_WplushadH_GE2J_MJJ_GT700_PTH_0_200_PTHJJ_0_25
	r_proc_WplushadH_rest
	r_proc_ZH_lep_PTV_0_150
	r_proc_ZH_lep_PTV_GT150
	r_proc_ZhadH_GE2J_MJJ_350_700_PTH_0_200_PTHJJ_0_25
	r_proc_ZhadH_GE2J_MJJ_60_120
	r_proc_ZhadH_GE2J_MJJ_GT350_PTH_0_200_PTHJJ_GT25
	r_proc_ZhadH_GE2J_MJJ_GT350_PTH_GT200
	r_proc_ZhadH_GE2J_MJJ_GT700_PTH_0_200_PTHJJ_0_25
	r_proc_ZhadH_rest
)

FAILED=()

for POI in "${POIS[@]}"; do
	SHORT="${POI#r_proc_}"
	NAME="scan1D.${SHORT}"
	ROOT_FILE="${TRIAL_DIR}/combine_output/higgsCombine.${NAME}.MultiDimFit.mH125.38.root"
	OUT_PNG="${PLOT_DIR}/scan1D_${SHORT}.png"

	echo "============================================================"
	echo "Plotting: ${POI}"
	echo "  input:  ${ROOT_FILE}"
	echo "  output: ${OUT_PNG}"
	echo "============================================================"

	if [[ ! -f "${ROOT_FILE}" ]]; then
		echo "WARNING: ROOT file not found, skipping: ${ROOT_FILE}"
		FAILED+=("${POI} (missing ROOT file)")
		continue
	fi

	if python3 "${PLOT_SCRIPT}" \
		--input  "${ROOT_FILE}" \
		--poi    "${POI}" \
		--output "${OUT_PNG}"; then
		echo "Saved: ${OUT_PNG}"
	else
		echo "WARNING: plot_1D_scan.py failed for ${POI}"
		FAILED+=("${POI} (plot script error)")
	fi
done

echo ""
echo "============================================================"
if [[ ${#FAILED[@]} -eq 0 ]]; then
	echo "All 1D scan plots done. Output directory:"
	echo "  ${PLOT_DIR}"
else
	echo "Completed with ${#FAILED[@]} failure(s):"
	for f in "${FAILED[@]}"; do echo "  - ${f}"; done
	echo "Successful plots saved to: ${PLOT_DIR}"
fi
echo "============================================================"
